options {
  JAVA_UNICODE_ESCAPE = true;
}

PARSER_BEGIN(MiniJavaParser)

package br.ufc.minijava.parser;

  public class MiniJavaParser {}

PARSER_END(MiniJavaParser)

/* 1. ANÁLISE LÉXICA: CARACTERES IGNORADOS */
SKIP : {
  " "
| "\t"
| "\n"
| "\r"
| < "//" (~["\n","\r"])* ("\n"|"\r"|"\r\n") >             // Comentário de linha
| < "/*" (~["*"])* "*" ("*" | (~["*","/"] (~["*"])* "*"))* "/" > // Comentário de bloco
}

/* 2. ANÁLISE LÉXICA: PALAVRAS RESERVADAS E OPERADORES */
TOKEN : {
  < CLASS: "class" >
| < PUBLIC: "public" >
| < STATIC: "static" >
| < VOID: "void" >
| < MAIN: "main" >
| < STRING: "String" >
| < EXTENDS: "extends" >
| < RETURN: "return" >
| < INT: "int" >
| < BOOLEAN: "boolean" >
| < IF: "if" >
| < ELSE: "else" >
| < WHILE: "while" >
| < PRINT: "System.out.println" >
| < TRUE: "true" >
| < FALSE: "false" >
| < THIS: "this" >
| < NEW: "new" >
| < LBRACE: "{" >
| < RBRACE: "}" >
| < LPAREN: "(" >
| < RPAREN: ")" >
| < LSQPAREN: "[" >
| < RSQPAREN: "]" >
| < SEMICOLON: ";" >
| < COMMA: "," >
| < DOT: "." >
| < ASSIGN: "=" >
| < LT: "<" >
| < PLUS: "+" >
| < MINUS: "-" >
| < TIMES: "*" >
| < DIVIDE: "/" >
| < AND: "&&" >
| < NOT: "!" >
}

/* 3. ANÁLISE LÉXICA: IDENTIFICADORES E NÚMEROS */
TOKEN : {
  < ID: ["a"-"z","A"-"Z"] ( ["a"-"z","A"-"Z","0"-"9","_"] )* >
| < INTEGER_LITERAL: ( ["0"-"9"] )+ >
}

/* 4. ANÁLISE SINTÁTICA */
// TODO: Substituir pelas regras do MiniJava (livro do Appel)

void Program() : {} {
  MainClass() ( ClassDeclaration() )* <EOF>
}

void MainClass() : {} {
  <CLASS> <ID> <LBRACE>
    <PUBLIC> <STATIC> <VOID> <MAIN> <LPAREN> <STRING> <LSQPAREN> <RSQPAREN> <ID> <RPAREN>
    <LBRACE> Statement() <RBRACE>
  <RBRACE>
}

void ClassDeclaration() : {} {
  <CLASS> <ID> [ <EXTENDS> <ID> ] <LBRACE> ( VarDeclaration() )* ( MethodDeclaration() )* <RBRACE>
}

// detalhar melhor depois:
void VarDeclaration() : {} {
  Type() <ID> <SEMICOLON>
}

void MethodDeclaration() : {} {
  <PUBLIC> Type() <ID> <LPAREN> [ FormalList() ] <RPAREN>
  <LBRACE> ( LOOKAHEAD(2) VarDeclaration() )* ( Statement() )* <RETURN> Expression() <SEMICOLON> <RBRACE>
}

void FormalList() : {} {
  Type() <ID> ( <COMMA> Type() <ID> )*
}

void Type() : {} {
  LOOKAHEAD(2) <INT> <LSQPAREN> <RSQPAREN> | <BOOLEAN> | <INT> | <ID>
}

void Statement() : {} {
    <LBRACE> ( Statement() )* <RBRACE>
  | <IF> <LPAREN> Expression() <RPAREN> Statement() <ELSE> Statement()
  | <WHILE> <LPAREN> Expression() <RPAREN> Statement()
  | <PRINT> <LPAREN> Expression() <RPAREN> <SEMICOLON>
  | LOOKAHEAD(2) <ID> <ASSIGN> Expression() <SEMICOLON>
  | <ID> <LSQPAREN> Expression() <RSQPAREN> <ASSIGN> Expression() <SEMICOLON>
}

void Expression() : {} {
    AndExpression()
}

void AndExpression() : {} {
    LessExpression() ( <AND> LessExpression() )*
}

void LessExpression() : {} {
    AdditiveExpression() ( <LT> AdditiveExpression() )*
}

void AdditiveExpression() : {} {
    MultiplicativeExpression() ( ( <PLUS> | <MINUS> ) MultiplicativeExpression() )*
}

void MultiplicativeExpression() : {} {
    PrimaryExpression() ( ( <TIMES> | <DIVIDE> ) PrimaryExpression() )*
}

void PrimaryExpression() : {} {
  (
      <INTEGER_LITERAL>
    | <TRUE>
    | <FALSE>
    | <ID>
    | <THIS>
    | LOOKAHEAD(3) <NEW> <INT> <LSQPAREN> Expression() <RSQPAREN>
    | <NEW> <ID> <LPAREN> <RPAREN>
    | <NOT> Expression()
    | <LPAREN> Expression() <RPAREN>
  )
  (
    // Sufixos que podem se repetir: a.metodo().outro[0]
    <LSQPAREN> Expression() <RSQPAREN>
    | LOOKAHEAD(2) <DOT> <ID> <LPAREN> [ ExpressionList() ] <RPAREN>
    | <DOT> "length"
  )*
}

void ExpressionList() : {} {
  Expression() ( <COMMA> Expression() )*
}